[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rusttype = "0.9.3"
printpdf = "0.6.0"
# ab_glyph = "0.2.21"
ab_glyph = { default-features = false, features = ["libm"] }
